<a href="https://colab.research.google.com/github/poncedanna08-rgb/AYP-2026/blob/main/CLASE_AYP_13_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INTRODUCCION A PANDAS**

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

Los Dataframes

In [5]:
pd.DataFrame(data=[(0,1,2), (1,2,3), (2,3,4), (3,4,5), (2,3)])

   0  1    2
0  0  1  2.0
1  1  2  3.0
2  2  3  4.0
3  3  4  5.0
4  2  3  NaN

In [8]:
diccionarios = {"curso1":[10,5,33,45,25,22],
                "curso2":[0,15,21,30,31,11],
                "curso3":[15,5,1,10,42,21],
                "curso4":[20,35,3,15,0,0]}

In [10]:
pd.DataFrame(data=diccionarios)

   curso1  curso2  curso3  curso4
0      10       0      15      20
1       5      15       5      35
2      33      21       1       3
3      45      30      10      15
4      25      31      42       0
5      22      11      21       0

In [13]:
import numpy as np

In [14]:
matriz = np.arange(9).reshape(3,3)

In [15]:
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
pd.DataFrame(matriz)

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

Indices

In [17]:
indice = ("enero", "febrero", "marzo", "abril", "mayo", "junio")

In [18]:
pd.DataFrame(data=diccionarios, index=indice)

         curso1  curso2  curso3  curso4
enero        10       0      15      20
febrero       5      15       5      35
marzo        33      21       1       3
abril        45      30      10      15
mayo         25      31      42       0
junio        22      11      21       0

In [19]:
pd.DataFrame(matriz, index=["uno", "dos", "tres"], columns=["a", "b", "c"])

      a  b  c
uno   0  1  2
dos   3  4  5
tres  6  7  8

In [20]:
cursos = {"curso1":[10,5,33,45,25,22],
                "curso2":[0,15,21,30,31,11],
                "curso3":[15,5,1,10,42,21],
                "curso4":[20,35,3,15,0,0]}

In [22]:
cursos = pd.DataFrame(data=cursos, index=indice)
cursos

         curso1  curso2  curso3  curso4
enero        10       0      15      20
febrero       5      15       5      35
marzo        33      21       1       3
abril        45      30      10      15
mayo         25      31      42       0
junio        22      11      21       0

In [23]:
cursos[["curso3", "curso4"]]

         curso3  curso4
enero        15      20
febrero       5      35
marzo         1       3
abril        10      15
mayo         42       0
junio        21       0

In [24]:
type(cursos["curso3"])

pandas.core.series.Series

In [27]:
import numpy as np

In [32]:
datos_np = np.arange(1,13).reshape(3,4)

In [33]:
datos_np

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
datos = pd.DataFrame(datos_np)

In [35]:
datos

   0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [36]:
datos[2]

0     3
1     7
2    11
Name: 2, dtype: int64

In [37]:
cursos[:1]

       curso1  curso2  curso3  curso4
enero      10       0      15      20

In [38]:
type(cursos[:1])

pandas.core.frame.DataFrame

In [39]:
cursos[::2]

       curso1  curso2  curso3  curso4
enero      10       0      15      20
marzo      33      21       1       3
mayo       25      31      42       0

In [40]:
cursos ["marzo": "mayo"]

       curso1  curso2  curso3  curso4
marzo      33      21       1       3
abril      45      30      10      15
mayo       25      31      42       0

In [44]:
cursos["curso1"][2]

/tmp/ipykernel_12496/1563643707.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cursos["curso1"][2]

np.int64(33)

In [45]:
cursos["curso1"]["marzo"]

np.int64(33)

In [46]:
cursos["curso2"][3:5]

abril    30
mayo     31
Name: curso2, dtype: int64

In [48]:
pd.Series([12,4,32,41,33,28], name = "py201")

0    12
1     4
2    32
3    41
4    33
5    28
Name: py201, dtype: int64

In [49]:
serie = pd.Series ([12,4,32,41,33,28], index = indice, name = "py201")

In [50]:
serie

enero      12
febrero     4
marzo      32
abril      41
mayo       33
junio      28
Name: py201, dtype: int64

In [51]:
import pandas as pd
import numpy as np
from datetime import datetime

In [52]:
indice = ['gerente', 'supervisor', 'vendedor', 'cajero']
personal = pd.DataFrame({'nombres':('Juan Pérez',
                                    'María Sánchez',
                                    'Jorge Vargas',
                                    'Rodrigo Martínez'),
            'fechas':(datetime(1995,12,21),
                      datetime(1989,1,13),
                      datetime(1992,9,14),
                      datetime(1993,7,8)),
            'saldo': (2500,
                      5345,
                      np.nan,
                      11323.2),
            'al corriente':(True,
                            True,
                            False,
                            True)}, index=indice)

In [53]:
personal

                     nombres     fechas    saldo  al corriente
gerente           Juan Pérez 1995-12-21   2500.0          True
supervisor     María Sánchez 1989-01-13   5345.0          True
vendedor        Jorge Vargas 1992-09-14      NaN         False
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [54]:
personal.shape

(4, 4)

In [55]:
personal.index

Index(['gerente', 'supervisor', 'vendedor', 'cajero'], dtype='object')

In [56]:
personal.columns

Index(['nombres', 'fechas', 'saldo', 'al corriente'], dtype='object')

In [59]:
personal.reset_index()

        index           nombres     fechas    saldo  al corriente
0     gerente        Juan Pérez 1995-12-21   2500.0          True
1  supervisor     María Sánchez 1989-01-13   5345.0          True
2    vendedor      Jorge Vargas 1992-09-14      NaN         False
3      cajero  Rodrigo Martínez 1993-07-08  11323.2          True

In [60]:
personal

                     nombres     fechas    saldo  al corriente
gerente           Juan Pérez 1995-12-21   2500.0          True
supervisor     María Sánchez 1989-01-13   5345.0          True
vendedor        Jorge Vargas 1992-09-14      NaN         False
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [61]:
personal.set_index("nombres")

                     fechas    saldo  al corriente
nombres
Juan Pérez       1995-12-21   2500.0          True
María Sánchez    1989-01-13   5345.0          True
Jorge Vargas     1992-09-14      NaN         False
Rodrigo Martínez 1993-07-08  11323.2          True

In [62]:
personal.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, gerente to cajero
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nombres       4 non-null      object
 1   fechas        4 non-null      datetime64[ns]
 2   saldo         3 non-null      float64
 3   al corriente  4 non-null      bool
dtypes: bool(1), datetime64[ns](1), float64(1), object(1)
memory usage: 304.0+ bytes

In [64]:
datos = pd.DataFrame(np.arange(20).reshape(5,4),
                     columns =("primero", "segundo", "tercero", "cuarto"))

In [65]:
datos

   primero  segundo  tercero  cuarto
0        0        1        2       3
1        4        5        6       7
2        8        9       10      11
3       12       13       14      15
4       16       17       18      19

In [66]:
datos.iloc[2,[3]]

cuarto    11
Name: 2, dtype: int64

In [67]:
type(datos.iloc[2,[3]])

pandas.core.series.Series

In [68]:
datos.iloc[2,[2,1,3]]

tercero    10
segundo     9
cuarto     11
Name: 2, dtype: int64

In [69]:
datos.iloc[2]

primero     8
segundo     9
tercero    10
cuarto     11
Name: 2, dtype: int64

In [70]:
personal.loc["supervisor", ["fechas"]]

fechas    1989-01-13 00:00:00
Name: supervisor, dtype: object

In [74]:
personal.loc["gerente",["fechas", "nombres"]]

fechas     1995-12-21 00:00:00
nombres             Juan Pérez
Name: gerente, dtype: object

In [75]:
personal["saldo"] > 3000

gerente       False
supervisor     True
vendedor      False
cajero         True
Name: saldo, dtype: bool

In [76]:
personal.loc[personal["saldo"] > 3000]

                     nombres     fechas    saldo  al corriente
supervisor     María Sánchez 1989-01-13   5345.0          True
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [77]:
personal.loc[personal["al corriente"]]

                     nombres     fechas    saldo  al corriente
gerente           Juan Pérez 1995-12-21   2500.0          True
supervisor     María Sánchez 1989-01-13   5345.0          True
cajero      Rodrigo Martínez 1993-07-08  11323.2          True

In [80]:
personal.loc[personal["al corriente"] == False]

               nombres     fechas  saldo  al corriente
vendedor  Jorge Vargas 1992-09-14    NaN         False

In [81]:
indice_1 = ("lunes", "martes", "miércoles")
marco_1 = pd.DataFrame({'Centro':[1520,1640,1043],
                       'Sur':[1422,1673,1534],
                      'Oriente':[1021,1073,1100]},
                       index=indice_1)

In [82]:
indice_2 = ("jueves", "viernes", "sábado")

marco_2 = pd.DataFrame({'Centro':[1321,1459,1875],

                       'Sur':[1622,1841,1920],

                      'Oriente':[1500,1432,1491]},

                      index=indice_2)

In [83]:
marco_1

           Centro   Sur  Oriente
lunes        1520  1422     1021
martes       1640  1673     1073
miércoles    1043  1534     1100

In [84]:
marco_2

         Centro   Sur  Oriente
jueves     1321  1622     1500
viernes    1459  1841     1432
sábado     1875  1920     1491

In [85]:
pd.concat([marco_1, marco_2])

           Centro   Sur  Oriente
lunes        1520  1422     1021
martes       1640  1673     1073
miércoles    1043  1534     1100
jueves       1321  1622     1500
viernes      1459  1841     1432
sábado       1875  1920     1491

In [86]:
pd.concat([marco_1, marco_2], axis=1)

           Centro     Sur  Oriente  Centro     Sur  Oriente
lunes      1520.0  1422.0   1021.0     NaN     NaN      NaN
martes     1640.0  1673.0   1073.0     NaN     NaN      NaN
miércoles  1043.0  1534.0   1100.0     NaN     NaN      NaN
jueves        NaN     NaN      NaN  1321.0  1622.0   1500.0
viernes       NaN     NaN      NaN  1459.0  1841.0   1432.0
sábado        NaN     NaN      NaN  1875.0  1920.0   1491.0

In [88]:
pd.concat([marco_1, marco_2], axis=1)["Centro"]

           Centro  Centro
lunes      1520.0     NaN
martes     1640.0     NaN
miércoles  1043.0     NaN
jueves        NaN  1321.0
viernes       NaN  1459.0
sábado        NaN  1875.0