<a href="https://colab.research.google.com/github/poncedanna08-rgb/AYP-2026/blob/main/CLASE_AYP_15_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Metodos groupby()**

In [ ]:
import pandas as pd
from datetime import datetime
facturas = pd.DataFrame({'folio':(15234,
                      15235,
                      15236,
                      15237,
                      15238,
                      15239,
                      15240,
                      15241,
                      15242),
             'sucursal':('CDMX01',
                         'MTY01',
                         'CDMX02',
                         'CDMX02',
                         'MTY01',
                         'GDL01',
                         'CDMX02',
                         'MTY01',
                         'GDL01'),
             'monto':(1420.00,
                     1532.00,
                     890.00,
                     1300.00,
                     3121.47,
                     1100.5,
                     12230,
                     230.85,
                     1569),
             'fecha':(datetime(2019,3,11,17,24),
                     datetime(2019,3,24,14,46),
                     datetime(2019,3,25,17,58),
                     datetime(2019,3,27,13,11),
                     datetime(2019,3,31,10,25),
                     datetime(2019,4,1,18,32),
                     datetime(2019,4,3,11,43),
                     datetime(2019,4,4,16,55),
                     datetime(2019,4,5,12,59)),
            'cliente':(19234,
                       19232,
                       19235,
                       19233,
                       19236,
                       19237,
                       19232,
                       19233,
                       19232)
                        })

In [ ]:
facturas

   folio sucursal     monto               fecha  cliente
0  15234   CDMX01   1420.00 2019-03-11 17:24:00    19234
1  15235    MTY01   1532.00 2019-03-24 14:46:00    19232
2  15236   CDMX02    890.00 2019-03-25 17:58:00    19235
3  15237   CDMX02   1300.00 2019-03-27 13:11:00    19233
4  15238    MTY01   3121.47 2019-03-31 10:25:00    19236
5  15239    GDL01   1100.50 2019-04-01 18:32:00    19237
6  15240   CDMX02  12230.00 2019-04-03 11:43:00    19232
7  15241    MTY01    230.85 2019-04-04 16:55:00    19233
8  15242    GDL01   1569.00 2019-04-05 12:59:00    19232

In [ ]:
gastos_por_cliente = facturas.filter(items=["monto", "cliente"])

In [ ]:
gastos_por_cliente

      monto  cliente
0   1420.00    19234
1   1532.00    19232
2    890.00    19235
3   1300.00    19233
4   3121.47    19236
5   1100.50    19237
6  12230.00    19232
7    230.85    19233
8   1569.00    19232

In [ ]:
clientes = gastos_por_cliente.groupby("cliente")

In [ ]:
clientes

In [ ]:
print(clientes.groups)

{19232: [1, 6, 8], 19233: [3, 7], 19234: [0], 19235: [2], 19236: [4], 19237: [5]}

In [ ]:
for nombre_cliente, grupo in clientes:
  print(f"Grupo para cliente: {nombre_cliente}")
  print(grupo)
  print("-" * 50)

Grupo para cliente: 19232
     monto  cliente
1   1532.0    19232
6  12230.0    19232
8   1569.0    19232
--------------------------------------------------
Grupo para cliente: 19233
     monto  cliente
3  1300.00    19233
7   230.85    19233
--------------------------------------------------
Grupo para cliente: 19234
    monto  cliente
0  1420.0    19234
--------------------------------------------------
Grupo para cliente: 19235
   monto  cliente
2  890.0    19235
--------------------------------------------------
Grupo para cliente: 19236
     monto  cliente
4  3121.47    19236
--------------------------------------------------
Grupo para cliente: 19237
    monto  cliente
5  1100.5    19237
--------------------------------------------------

In [ ]:
clientes.size()

cliente
19232    3
19233    2
19234    1
19235    1
19236    1
19237    1
dtype: int64

In [ ]:
clientes.mean()

               monto
cliente
19232    5110.333333
19233     765.425000
19234    1420.000000
19235     890.000000
19236    3121.470000
19237    1100.500000

In [ ]:
clientes.min()

           monto
cliente
19232    1532.00
19233     230.85
19234    1420.00
19235     890.00
19236    3121.47
19237    1100.50

In [ ]:
clientes.max()

            monto
cliente
19232    12230.00
19233     1300.00
19234     1420.00
19235      890.00
19236     3121.47
19237     1100.50